layers = {
    "Ủy ban nhân dân": "gov-office",
    "Cơ quan nhà nước": "gov-agency",
    "Đại sứ quán": "embassy",
    "Kho bạc": "treasury",
    "Cơ quan thuế": "tax-agency",
    "Công an": "police",
    "Bệnh viện": "hospital",
    "Phòng khám": "clinic",
    "Nha khoa": "dental-clinic",
    "Nhà Thuốc": "pharmacy",
    "Trung tâm tiêm chủng": "vaccination-center",
    "Trạm y tế": "health-station",
    "Trung tâm y tế": "health-center",
    "Đại học cao đẳng": "university-college",
    "Tiểu học": "primary-school",
    "Trung học cơ sở": "secondary-school",
    "Trung học Phổ thông": "high-school",
    "Nhà trẻ - Mẫu giáo": "kindergarten",
    "Trung tâm giáo dục": "education-center",
    "Nhà sách": "bookstore",
    "Thư viện": "library",
    "Trung tâm thương mại": "shopping-center",
    "Siêu thị": "supermarket",
    "Chợ": "market",
    "Cửa hàng": "store",
    "Bảo Tàng": "museum",
    "Công viên": "park",
    "Địa danh": "landmark",
    "Di tích lịch sử": "historic-site",
    "Nhà khách": "guesthouse",
    "Đình, đền, chùa, nhà thờ": "temple-shrine",
    "Biển, Đảo": "beach-island",
    "Quán ăn": "restaurant",
    "Quán Cafe": "food-stall",
    "Tiệm bánh": "cafe",
    "Quán Bia": "bakery",
    "Nhà hàng": "beer-pub",
    "Khu vui chơi": "entertainment-center",
    "Quán Karaoke": "karaoke",
    "Quán Bar": "bar",
    "Billiards": "billiards",
    "Rạp chiếu phim": "cinema",
    "Phòng trà ca nhạc": "music-lounge",
    "Sân bóng đá": "soccer-field",
    "Sân Golf": "golf-course",
    "Sân tennis": "tennis-court",
    "Bể bơi": "swimming-pool",
    "Trung tâm tổ chức sự kiện": "event-center",
    "Spa/Massage": "spa-massage",
    "Thể dục thẩm mỹ": "fitness-center",
    "Tiệm nail": "nail-salon",
    "Chăm sóc da": "skincare",
    "Shop hóa mỹ phẩm": "cosmetic-store",
    "Thể dục thể thao": "gym",
    "Thẩm mỹ viện": "aesthetic-clinic",
    "Làm tóc": "hair-salon",
    "Studio ảnh": "photo-studio",
    "Thời trang": "fashion-store",
    "Khách sạn": "hotel",
    "Nhà nghỉ": "motel",
    "Homestay": "homestay",
    "Resort": "resort",
    "Phòng vé": "ticket-office",
    "Ngân hàng": "bank",
    "Công ty": "company",
    "Công ty bảo hiểm": "insurance-company",
    "Coworking Space": "coworking-space",
    "Bến xe": "bus-station",
    "Xe bus": "bus-stop",
    "Cây xăng": "fuel",
    "Hãng Taxi": "taxi-company",
    "Nhà xe": "transport-company",
    "Gara ô tô": "car-garage",
    "Showroom ô tô": "car-showroom",
    "Đại lý xe máy": "motorbike-dealer",
    "Sân bay": "airport",
    "Nhà ga": "train-station",
    "Trung tâm đào tạo lái xe": "driving-school",
    "Đơn vị vận chuyển": "delivery-service",
    "Xe tải, taxi tải": "truck-service",
    "Xe 3 bánh chở hàng": "cargo-tricycle",
    "Xe limousine": "limousine-service",
    "Trung tâm đăng kiểm": "inspection-center",
    "Dự án khu căn hộ cao cấp": "apartment-project",
    "Dự án biệt thự": "villa-project",
    "Khu du lịch nghỉ dưỡng": "resort-project",
    "Dự án dân cư": "residential-project",
    "Dự án Cao ốc văn phòng": "office-building-project",
    "Dự án khu công nghiệp": "industrial-zone-project",
    "Dự án đất chia lô": "land-project",
    "Dự án trung tâm thương mại": "mall-project",
    "Dự án căn hộ trung cư": "condominium-project",
    "Dịch vụ Vệ sinh": "cleaning-service",
    "Khác": "other-services",
    "Kho xưởng": "warehouse-factory"
}
